spring:
  application:
    name: fx-deals-sdet
  datasource:
    url: jdbc:postgresql://localhost:5432/fxdeals
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
